# Generated by Django 4.0.5 on 2022-07-04 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=15)),
                ('batch_time', models.DateTimeField(auto_now_add=True)),
                ('escalations', models.CharField(max_length=126)),
                ('uploaded_by', models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnalysedPlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('array_code', models.CharField(max_length=6)),
                ('batch', models.CharField(max_length=13)),
                ('date_in', models.DateTimeField(auto_now_add=True)),
                ('araya', models.CharField(max_length=8)),
                ('pl_384', models.TextField()),
                ('uploaded_by', models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
