# Generated by Django 4.0.5 on 2022-07-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0002_alter_analysedplate_uploaded_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thresholds', models.TextField()),
                ('globals', models.TextField()),
                ('queries', models.TextField()),
                ('plotly_js', models.TextField()),
            ],
        ),
    ]
