# Generated by Django 4.0.5 on 2022-07-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0003_config'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Config',
        ),
        migrations.AddField(
            model_name='analysedplate',
            name='in_ff',
            field=models.BooleanField(default=True),
        ),
    ]
