# Generated by Django 4.0.5 on 2022-07-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0004_delete_config_analysedplate_in_ff'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysedplate',
            name='pool',
            field=models.CharField(default='POOL00080237', max_length=12),
            preserve_default=False,
        ),
    ]
