# Generated by Django 4.0.5 on 2022-07-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0005_analysedplate_pool'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolFinderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thresholds', models.TextField()),
                ('globals', models.TextField()),
                ('queries', models.TextField()),
                ('plotly_js', models.TextField()),
            ],
        ),
    ]
