# Generated by Django 4.0.5 on 2022-07-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0006_poolfinderconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArayaThresholds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('araya', models.CharField(max_length=7)),
                ('positive', models.FloatField()),
                ('negative', models.FloatField()),
                ('nvic', models.FloatField()),
                ('low_rox', models.IntegerField()),
                ('high_rox', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='PoolFinderConfig',
        ),
    ]
