# Generated by Django 4.0.5 on 2022-07-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0007_arayathresholds_delete_poolfinderconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolFinderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=100)),
                ('value', models.TextField()),
            ],
        ),
    ]
