# Generated by Django 4.0.5 on 2022-07-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0008_poolfinderconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='in_ff',
            field=models.BooleanField(default=True),
        ),
    ]
