# Generated by Django 4.0.5 on 2022-07-08 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0009_batch_in_ff'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysedplate',
            name='escalated',
            field=models.BooleanField(default=False),
        ),
    ]
