# Generated by Django 4.0.5 on 2022-07-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0011_alter_analysedplate_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysedplate',
            name='pl_q1',
            field=models.TextField(default='NONE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysedplate',
            name='pl_q2',
            field=models.TextField(default='Not added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysedplate',
            name='pl_q3',
            field=models.TextField(default='Not added'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysedplate',
            name='pl_q4',
            field=models.TextField(default='not added'),
            preserve_default=False,
        ),
    ]
