# Generated by Django 4.0.5 on 2022-07-14 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0012_analysedplate_pl_q1_analysedplate_pl_q2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysedplate',
            name='escalations',
            field=models.TextField(default='No Escalations based on the SOP, \n    however service guidance escalations have not been considered'),
        ),
        migrations.AddField(
            model_name='analysedplate',
            name='pl_comments',
            field=models.TextField(default='Unavailable'),
        ),
        migrations.AddField(
            model_name='analysedplate',
            name='pl_nfvnv',
            field=models.TextField(default='NONE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysedplate',
            name='pl_rvf',
            field=models.TextField(default='NONE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysedplate',
            name='pl_rvnf',
            field=models.TextField(default='NONE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysedplate',
            name='pl_rvnv',
            field=models.TextField(default='NONE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysedplate',
            name='pl_rvv',
            field=models.TextField(default='NONE'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysedplate',
            name='plate_info',
            field=models.TextField(default='Unavailable'),
        ),
        migrations.AddField(
            model_name='analysedplate',
            name='roxbox',
            field=models.TextField(default='NONE'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analysedplate',
            name='araya',
            field=models.CharField(default='Unknown', max_length=8),
        ),
        migrations.AlterField(
            model_name='analysedplate',
            name='pool',
            field=models.CharField(default='NONE', max_length=12),
        ),
    ]
