# Generated by Django 4.0.5 on 2022-07-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0013_analysedplate_escalations_analysedplate_pl_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysedplate',
            name='prio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analysedplate',
            name='repooled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analysedplate',
            name='restamped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='analysedplate',
            name='vip',
            field=models.BooleanField(default=False),
        ),
    ]
