# Generated by Django 4.0.5 on 2022-07-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0014_analysedplate_prio_analysedplate_repooled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch',
            field=models.TextField(default='Buffer Summary Unavailable'),
        ),
    ]
