# Generated by Django 4.0.5 on 2022-07-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0015_alter_batch_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='summary',
            field=models.TextField(default='Buffer Summary Unavailable'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch',
            field=models.CharField(max_length=15),
        ),
    ]
