# Generated by Django 4.0.5 on 2022-07-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0016_batch_summary_alter_batch_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='buffers',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='batch',
            name='prio_plates',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='batch',
            name='vip_plates',
            field=models.CharField(default='', max_length=128),
        ),
    ]
