# Generated by Django 4.0.5 on 2022-07-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0017_batch_buffers_batch_prio_plates_batch_vip_plates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysedplate',
            name='escalations',
        ),
        migrations.AddField(
            model_name='analysedplate',
            name='escalation_reason',
            field=models.TextField(default='NONE'),
        ),
    ]
