# Generated by Django 4.0.5 on 2022-07-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0018_remove_analysedplate_escalations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysedplate',
            name='id',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='id',
        ),
        migrations.RemoveField(
            model_name='poolfinderconfig',
            name='id',
        ),
        migrations.AlterField(
            model_name='analysedplate',
            name='array_code',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='poolfinderconfig',
            name='option',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
