# Generated by Django 4.0.5 on 2022-07-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0019_remove_analysedplate_id_remove_batch_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysedplate',
            name='array_code',
            field=models.CharField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
