# Generated by Django 4.0.5 on 2022-07-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0020_alter_analysedplate_array_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch',
            field=models.CharField(max_length=18, primary_key=True, serialize=False),
        ),
    ]
