# Generated by Django 4.0.5 on 2022-07-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0021_alter_batch_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='plates',
            field=models.CharField(default='NONE', max_length=158),
            preserve_default=False,
        ),
    ]
