# Generated by Django 4.0.5 on 2022-07-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0022_batch_plates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='plates',
            field=models.CharField(default='', max_length=158),
        ),
    ]
