# Generated by Django 4.0.5 on 2022-07-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0023_alter_batch_plates'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysedplate',
            name='show_in_plates_in_fastfinder',
            field=models.BooleanField(default=True),
        ),
    ]
