# Generated by Django 4.0.5 on 2022-07-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0024_analysedplate_show_in_plates_in_fastfinder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch',
            old_name='vip_plates',
            new_name='plates_to_do',
        ),
    ]
