# Generated by Django 4.0.5 on 2022-07-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0025_rename_vip_plates_batch_plates_to_do'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='vip_plates',
            field=models.CharField(default='', max_length=128),
        ),
    ]
