# Generated by Django 4.0.5 on 2022-07-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0027_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysedplate',
            name='date_in',
            field=models.DateTimeField(),
        ),
    ]
