# Generated by Django 4.0.5 on 2022-08-02 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0029_alter_batch_batch_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.CharField(max_length=9)),
                ('x384_well', models.CharField(max_length=3)),
                ('fam', models.IntegerField()),
                ('vic', models.IntegerField()),
                ('rox', models.IntegerField()),
                ('flag', models.CharField(max_length=20)),
                ('barcode', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='analysedplate',
            name='pl_384',
        ),
        migrations.RemoveField(
            model_name='analysedplate',
            name='pl_nfvnv',
        ),
        migrations.RemoveField(
            model_name='analysedplate',
            name='pl_q1',
        ),
        migrations.RemoveField(
            model_name='analysedplate',
            name='pl_q2',
        ),
        migrations.RemoveField(
            model_name='analysedplate',
            name='pl_q3',
        ),
        migrations.RemoveField(
            model_name='analysedplate',
            name='pl_q4',
        ),
        migrations.RemoveField(
            model_name='analysedplate',
            name='pl_rvf',
        ),
        migrations.RemoveField(
            model_name='analysedplate',
            name='pl_rvnf',
        ),
        migrations.RemoveField(
            model_name='analysedplate',
            name='pl_rvnv',
        ),
        migrations.RemoveField(
            model_name='analysedplate',
            name='pl_rvv',
        ),
    ]
