# Generated by Django 4.0.5 on 2022-08-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0030_sample_remove_analysedplate_pl_384_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='plate',
            field=models.CharField(db_index=True, max_length=9),
        ),
    ]
