# Generated by Django 4.0.5 on 2022-08-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0031_alter_sample_plate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='nfam',
            field=models.FloatField(default='1.0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sample',
            name='nvic',
            field=models.FloatField(default='1.0'),
            preserve_default=False,
        ),
    ]
