# Generated by Django 4.0.5 on 2022-08-03 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0032_sample_nfam_sample_nvic'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sample',
            unique_together={('plate', 'x384_well')},
        ),
    ]
