# Generated by Django 4.0.5 on 2022-08-03 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0033_alter_sample_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='plate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poolFinder.analysedplate'),
        ),
    ]
