# Generated by Django 4.0.5 on 2022-08-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0034_alter_sample_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysedplate',
            name='batch',
            field=models.CharField(max_length=18),
        ),
    ]
