# Generated by Django 4.0.5 on 2022-08-05 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0035_alter_analysedplate_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysedplate',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poolFinder.batch'),
        ),
    ]
