# Generated by Django 4.0.5 on 2022-08-10 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0036_alter_analysedplate_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlateSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_location', models.CharField(max_length=3)),
                ('positives', models.SmallIntegerField()),
                ('plods', models.SmallIntegerField()),
                ('negatives', models.SmallIntegerField()),
                ('vic_fails', models.SmallIntegerField()),
                ('total_samples', models.SmallIntegerField()),
                ('inact_plate', models.CharField(max_length=13)),
                ('nexar_or_dwp_ham', models.CharField(max_length=10)),
                ('araya_or_elute', models.CharField(max_length=13)),
                ('hydrocycler_or_kf', models.CharField(max_length=11)),
                ('df_or_384_ham', models.CharField(max_length=11)),
                ('plate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poolFinder.analysedplate')),
            ],
            options={
                'unique_together': {('plate', 'plate_location')},
            },
        ),
    ]
