# Generated by Django 4.0.5 on 2022-08-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0037_platesummary'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysedplate',
            name='average_rox',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysedplate',
            name='patient_rox_below_threshold',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysedplate',
            name='rox_above_threshold',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysedplate',
            name='rox_sd',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='analysedplate',
            name='total_rox_below_threshold',
            field=models.SmallIntegerField(default=0),
        ),
    ]
