# Generated by Django 4.0.5 on 2022-08-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0038_analysedplate_average_rox_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysedplate',
            name='high_plods',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='platesummary',
            name='negatives',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='platesummary',
            name='plods',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='platesummary',
            name='positives',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='platesummary',
            name='total_samples',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='platesummary',
            name='vic_fails',
            field=models.SmallIntegerField(default=0),
        ),
    ]
