# Generated by Django 4.0.5 on 2022-08-11 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0039_analysedplate_high_plods_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysedplate',
            name='plate_info',
        ),
        migrations.RemoveField(
            model_name='analysedplate',
            name='roxbox',
        ),
    ]
