# Generated by Django 3.2.13 on 2022-08-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0040_remove_analysedplate_plate_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arayathresholds',
            name='lj_mean_accu',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arayathresholds',
            name='lj_mean_qneg',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arayathresholds',
            name='lj_mean_qpos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arayathresholds',
            name='lj_sd_accu',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arayathresholds',
            name='lj_sd_qneg',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='arayathresholds',
            name='lj_sd_qpos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
