# Generated by Django 3.2.13 on 2022-08-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0041_auto_20220812_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arayathresholds',
            name='high_rox',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='arayathresholds',
            name='lj_mean_accu',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='arayathresholds',
            name='lj_mean_qneg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='arayathresholds',
            name='lj_mean_qpos',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='arayathresholds',
            name='lj_sd_accu',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='arayathresholds',
            name='lj_sd_qneg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='arayathresholds',
            name='lj_sd_qpos',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='arayathresholds',
            name='low_rox',
            field=models.FloatField(),
        ),
    ]
