# Generated by Django 3.2.13 on 2022-08-12 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0042_auto_20220812_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arayathresholds',
            name='araya',
            field=models.CharField(max_length=8),
        ),
    ]
