# Generated by Django 3.2.13 on 2022-08-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0043_alter_arayathresholds_araya'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='batch',
            field=models.CharField(default='NONE', max_length=18),
        ),
    ]
