# Generated by Django 3.2.13 on 2022-08-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0044_sample_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='araya',
            field=models.CharField(default='Unknown', max_length=8),
        ),
    ]
