# Generated by Django 3.2.13 on 2022-08-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0045_batch_araya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='nfam',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='nvic',
            field=models.FloatField(null=True),
        ),
    ]
