# Generated by Django 3.2.13 on 2022-08-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0046_auto_20220830_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arayathresholds',
            name='lj_mean_accu',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='arayathresholds',
            name='lj_mean_qneg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='arayathresholds',
            name='lj_mean_qpos',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='arayathresholds',
            name='lj_sd_accu',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='arayathresholds',
            name='lj_sd_qneg',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='arayathresholds',
            name='lj_sd_qpos',
            field=models.FloatField(default=0),
        ),
    ]
