# Generated by Django 3.2.13 on 2022-09-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poolFinder', '0047_auto_20220831_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysedplate',
            name='average_rox',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='analysedplate',
            name='rox_sd',
            field=models.IntegerField(default=0),
        ),
    ]
